import { ArrowRight, BarChart3, Camera, CheckCircle2, ChevronRight, Globe2, Map, Recycle, Route, ShieldCheck, Sparkles, Truck, Users } from "lucide-react";
import Link from "next/link";
import { AnimatedAiDetection } from "@/components/landing/AnimatedAiDetection";
import { AIStatusPill, ArrowPill, CivicCopilot } from "@/components/landing/CivicCopilot";

const FEATURES = [
  [Camera, "One-minute reporting", "A frictionless mobile flow for photo, GPS and context — no long civic forms."],
  [Sparkles, "Explainable AI", "11 waste categories, confidence scores and a human review path when the model is unsure."],
  [Map, "Live civic map", "See neighbourhood-level hotspots and give operations teams the precision they need."],
  [Route, "Smarter dispatch", "Bundle reports into practical routes so crews spend less time driving and more time cleaning."],
  [ShieldCheck, "Proof of resolution", "Every clean-up has a status trail and a completion photo before it is closed."],
  [BarChart3, "Better decisions", "Turn daily reports into category, SLA and hotspot intelligence for city leaders."],
] as const;

const ROLES = [
  { icon: Users, name: "Citizens", copy: "Spot a problem, snap the evidence and stay informed.", href: "/signin", color: "text-sky-300" },
  { icon: Truck, name: "Collection crews", copy: "Get the right location, hazard context and route sequence.", href: "/signin", color: "text-amber-300" },
  { icon: Globe2, name: "City operators", copy: "Triage the queue, dispatch work and monitor resolution.", href: "/signin", color: "text-forest-300" },
];

export default function LandingPage() {
  return <div className="relative min-h-dvh overflow-hidden bg-surface-950 text-[#ecf8f1]"><div className="aurora" aria-hidden />
    <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Link href="/" className="flex items-center gap-2.5"><span className="relative flex size-10 items-center justify-center rounded-2xl bg-gradient-primary font-display text-xl font-black text-white shadow-glow-forest">B</span><span className="font-display text-xl font-bold tracking-tight text-white">binit<span className="ml-1 text-xs font-medium text-forest-300/70">civic intelligence</span></span></Link><nav className="hidden items-center gap-7 text-sm text-forest-100/55 md:flex"><a href="#how" className="transition hover:text-white">How it works</a><a href="#platform" className="transition hover:text-white">Platform</a><a href="#zones" className="transition hover:text-white">Coverage</a></nav><div className="flex items-center gap-2"><Link href="/signin" className="rounded-xl px-3.5 py-2 text-sm font-semibold text-forest-100/75 transition hover:bg-white/5 hover:text-white">Sign in</Link><Link href="/signin" className="hidden items-center gap-1.5 rounded-xl bg-gradient-primary px-4 py-2 text-sm font-bold text-white shadow-glow-forest transition hover:brightness-110 sm:inline-flex">Open workspace <ArrowRight className="size-3.5" /></Link></div></header>
    <main className="relative z-[1] mx-auto max-w-7xl px-5 sm:px-8">
      <section className="grid items-center gap-12 pb-20 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:pb-28 lg:pt-20"><div><AIStatusPill /><h1 className="mt-6 max-w-3xl font-display text-5xl font-bold leading-[.98] tracking-[-.04em] text-white sm:text-7xl">Clean streets start with <span className="gradient-text text-glow">better signals.</span></h1><p className="mt-6 max-w-xl text-base leading-relaxed text-forest-100/60 sm:text-lg">Binit connects citizens, AI and collection teams in one calm, accountable loop — from the first photo to a verified clean-up.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/signin" className="group inline-flex items-center gap-2 rounded-xl bg-gradient-primary px-6 py-3.5 font-bold text-white shadow-glow-forest transition hover:-translate-y-0.5 hover:brightness-110">Report waste <ArrowPill /></Link><a href="#platform" className="inline-flex items-center gap-2 rounded-xl bg-white/[0.05] px-6 py-3.5 font-semibold text-forest-100/80 ring-1 ring-white/10 transition hover:bg-white/10">See the platform <ChevronRight className="size-4" /></a></div><div className="mt-9 flex flex-wrap gap-5 text-xs text-forest-100/45"><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-forest-400" />11 AI categories</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-forest-400" />Privacy-aware maps</span><span className="flex items-center gap-2"><CheckCircle2 className="size-4 text-forest-400" />Proof-verified closure</span></div></div><AnimatedAiDetection /></section>
      <section id="platform" className="py-16"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[.22em] text-forest-400">Built for the whole loop</p><h2 className="font-display text-3xl font-bold tracking-tight text-white sm:text-4xl">From signal to solution.</h2></div><p className="max-w-sm text-sm leading-relaxed text-forest-100/45">A focused operations layer for cleaner neighbourhoods, not another complaint inbox.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{FEATURES.map(([Icon, title, copy]) => <div key={title} className="group glass rounded-2xl p-5 transition duration-300 hover:-translate-y-1 hover:border-forest-500/35 hover:shadow-lift"><div className="mb-5 flex size-11 items-center justify-center rounded-xl bg-forest-500/15 text-forest-400 ring-1 ring-forest-500/25"><Icon className="size-5" /></div><h3 className="font-display text-base font-bold text-white">{title}</h3><p className="mt-2 text-sm leading-relaxed text-forest-100/55">{copy}</p></div>)}</div></section>
      <section id="how" className="py-16"><div className="glass-strong overflow-hidden rounded-3xl p-7 sm:p-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="mb-2 text-[11px] font-bold uppercase tracking-[.22em] text-amber-300/80">The Binit loop</p><h2 className="font-display text-3xl font-bold tracking-tight text-white sm:text-4xl">Less noise.<br /><span className="gradient-text">More action.</span></h2><p className="mt-4 text-sm leading-relaxed text-forest-100/55">Every report becomes structured intelligence that a real person can act on and a citizen can follow.</p></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{["Spot", "Snap", "Analyze", "Prioritize", "Locate", "Dispatch", "Resolve", "Improve"].map((step, index) => <div key={step} className="rounded-2xl bg-white/[.035] p-4 ring-1 ring-white/[.07]"><span className="font-mono text-xs text-forest-400/60">0{index + 1}</span><p className="mt-5 text-sm font-bold text-white">{step}</p></div>)}</div></div></div></section>
      <section id="zones" className="py-16"><div className="mb-8 text-center"><p className="mb-2 text-[11px] font-bold uppercase tracking-[.22em] text-sky-300/80">One platform, two contexts</p><h2 className="font-display text-3xl font-bold tracking-tight text-white sm:text-4xl">Designed for real places.</h2></div><div className="grid gap-4 md:grid-cols-2"><div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#112d20] to-[#08130e] p-7 ring-1 ring-forest-500/25"><div className="absolute -right-12 -top-12 size-44 rounded-full bg-forest-500/20 blur-3xl" /><Recycle className="relative size-7 text-forest-300" /><h3 className="relative mt-8 font-display text-2xl font-bold text-white">Kolkata Urban</h3><p className="relative mt-2 max-w-md text-sm leading-relaxed text-forest-100/55">High-density packaging, blocked drains and overflowing stations across Park Street, Salt Lake, Esplanade and Gariahat.</p><p className="relative mt-6 font-mono text-xs text-forest-300/70">22.5726° N · 88.3639° E</p></div><div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#2b2111] to-[#151007] p-7 ring-1 ring-amber-500/25"><div className="absolute -right-12 -top-12 size-44 rounded-full bg-amber-500/15 blur-3xl" /><Map className="relative size-7 text-amber-300" /><h3 className="relative mt-8 font-display text-2xl font-bold text-white">Rajarhat Panchayat</h3><p className="relative mt-2 max-w-md text-sm leading-relaxed text-amber-100/55">Illegal dumping along canals, pond pollution and village road litter served by local collection crews.</p><p className="relative mt-6 font-mono text-xs text-amber-300/70">22.6105° N · 88.5122° E</p></div></div></section>
      <section className="pb-24 pt-16"><div className="rounded-3xl bg-gradient-to-br from-[#0d291c] via-[#0b1e15] to-[#07110c] p-8 text-center ring-1 ring-forest-500/25 sm:p-14"><p className="text-[11px] font-bold uppercase tracking-[.22em] text-forest-400">Start the change</p><h2 className="mx-auto mt-3 max-w-2xl font-display text-3xl font-bold tracking-tight text-white sm:text-5xl">One photo can move a whole system.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-relaxed text-forest-100/55">Explore the citizen, crew or operator experience and see how Binit closes the loop.</p><Link href="/signin" className="mt-7 inline-flex items-center gap-2 rounded-xl bg-gradient-primary px-7 py-3.5 font-bold text-white shadow-glow-forest transition hover:brightness-110">Enter Binit <ArrowRight className="size-4" /></Link></div></section>
    </main><footer className="border-t border-white/[.08] py-8 text-center text-sm text-forest-100/35"><p>binit · <span className="gradient-text font-semibold">Smarter waste. Cleaner tomorrow.</span></p></footer><CivicCopilot /></div>;
}
